version: "3.3"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx-bread-bot.crt:/ssl/nginx-bread-bot.crt
      - /root/nginx-bread-bot.key:/ssl/nginx-bread-bot.key
    depends_on:
      - bread_bot
    networks:
      - bread_bot_net
  bread_bot:
    image: levkey/bread_bot:app
    restart: unless-stopped
    command: bash -c "alembic upgrade head && python server.py"
    ports:
      - "9090:9090"
    env_file:
      - /root/environments.env
    networks:
      - bread_bot_net
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /root/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    env_file:
      - /root/postgres.env
    ports:
      - "5432:5432"
    networks:
      - bread_bot_net
networks:
  bread_bot_net:
    external: True
volumes:
    pgdata: