name: RELEASE
on:
  push:
    branches:
      - main
jobs:
  testing:
    name: Testing
    uses: LEVLLN/bread_bot/.github/workflows/testing.yml@main
  build:
    needs: testing
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push base image
      uses: docker/build-push-action@v3
      with:
        file: ci/Dockerfile
        push: true
        tags: levkey/bread_bot:base
    - name: Build and push app image
      uses: docker/build-push-action@v3
      with:
        file: ci/Dockerfile.app
        push: true
        tags: levkey/bread_bot:app
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: ci
        path: ci
    - name: copy-files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "ci/*"
        target: "/root/"
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker pull levkey/bread_bot:app && docker-compose -p root -f ci/docker-compose.yml up -d --force-recreate
